#!/bin/sh
#
# Copyright 2023 Chainguard, Inc.
# Author: Dustin Kirkland <kirkland@chainguard.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Simple maintainer script to update the README.md with the help text from the wolfi-rc itself
# in the interest of keeping the two in sync

sed -i -n '/^## wolfi-rc commands/q;p' README.md

grep -A99999 "^## wolfi-rc commands" wolfi-rc | grep -B99999 -m1  "^\"" | grep -v "^\"$" >> README.md
